# -*- mode: python ; coding: utf-8 -*-
#
# PyInstaller spec for Dota 2 Tracker
#
# Build:
#   pip install pyinstaller
#   pyinstaller dota_tracker.spec
#
# Output: dist/dota-tracker/
#   dota-tracker.exe   ← double-click to run
#   static/            ← dashboard HTML (bundled)
#   data/              ← created on first run
#   friends.json       ← user edits this to add their Steam IDs
#
# Zip dist/dota-tracker/ and upload to GitHub Releases.

import sys
from pathlib import Path

ROOT = Path(SPECPATH)

# ── Source files to bundle alongside the exe ─────────────────────────────────
datas = [
    (str(ROOT / "static"), "static"),
]

# friends.json + every per-group data file are generated by the launcher on
# first run via app.data_pipeline.run_full_pipeline -- nothing user-specific
# from the developer's machine is bundled with the exe.
#
# The only data file we DO ship is model_weights.json (calibrated signal weights),
# which is group-agnostic -- the same weights work for any group's draft predictions.
weights = ROOT / "data" / "model_weights.json"
if weights.exists():
    datas.append((str(weights), "data"))

# ── Hidden imports that PyInstaller's static analysis misses ─────────────────
hidden = [
    # uvicorn loads these dynamically via importlib
    "uvicorn.logging",
    "uvicorn.loops",
    "uvicorn.loops.auto",
    "uvicorn.loops.asyncio",
    "uvicorn.protocols",
    "uvicorn.protocols.http",
    "uvicorn.protocols.http.auto",
    "uvicorn.protocols.http.h11_impl",
    "uvicorn.protocols.websockets",
    "uvicorn.protocols.websockets.auto",
    "uvicorn.lifespan",
    "uvicorn.lifespan.on",
    "uvicorn.lifespan.off",
    # anyio backend selected at runtime
    "anyio._backends._asyncio",
    # fastapi / starlette internals
    "fastapi.routing",
    "starlette.routing",
    "starlette.middleware.cors",
    # pandas parquet support
    "pyarrow",
    "pyarrow.parquet",
    # pydantic v2 core
    "pydantic_core",
    "pydantic_settings",
]

a = Analysis(
    ["launcher.py"],
    pathex=[str(ROOT)],
    binaries=[],
    datas=datas,
    hiddenimports=hidden,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # not needed at runtime
        "matplotlib", "notebook", "jupyter", "IPython",
        "scipy",        # only used in notebook calibration
        "pyarrow.tests",
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,     # --onedir: keep dlls in the folder, not embedded
    name="dota-tracker",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,              # keep console so users see startup message / errors
    disable_windowed_traceback=False,
    argv_emulation=False,
    icon=None,                 # add an .ico path here if you have one
    contents_directory=".",    # put bundled files next to the exe (not in _internal/)
                               # so users can find friends.json, data/, etc. directly
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="dota-tracker",       # → dist/dota-tracker/
)
